USB_VID = 0x303A
USB_PID = 0x8000
USB_PRODUCT = "EP-MOTHER-V2"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_SIZE = 8MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 2MB
CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_FREQ = 80m

#CIRCUITPY_USB = 1
CIRCUITPY_ESPCAMERA = 0
#DEBUG = 0
